version = "1"
daily_data = { "name" = "daily meditation data", schedule = "0 1/15 * * * *", enabled = true }
clean_data = { "name" = "clean outdated meditation scripts", schedule = "0 0 0 * * *", enabled = true }
